### ISSUE TITLE
Menu Project

### ISSUE THREAD

**Issue by smalluk** [john-smilga/javascript-basic-projects#129]
At 2:33:00 in the video you show code like this:
```
const menu = [array];
const sectionCenter = document.querySelector('.section-center');

window.addEventListener('DOMContentLoaded', function() {
  let displayMenu = menu.map(function (item) {
    // console.log(item);
    return "<h1>${item.title}</h1>";
  });
  console.log(displayMenu);
});
```
and your devtools console shows the array as being the 9 titles of the items but mine just shows the string 
```
"<h1>${item.title}</h1>"
```
nine times. Has something changed since the creation of the tutorial or have I made a mistake?

**Comment by pankajkandpal99** [comment]
const menu = [
  { title: 'Item 1' },
  { title: 'Item 2' },
  { title: 'Item 3' }
];

const sectionCenter = document.querySelector('.section-center');

window.addEventListener('DOMContentLoaded', function() {
  let displayMenu = menu.map(function(item) {
    return `<h1>${item.title}</h1>`;
  });
  console.log(displayMenu);
});


this is the right version......The template string should use backticks (``) instead of regular quotes for string interpolation. So, it should be `<h1>${item.title}</h1>` instead of "<h1>${item.title}</h1>".....

**Comment by Ashish-sarmah** [comment]
Just replace inverted commas with backtics(`<h1>${item.title}</h1>`)

**Comment by Nourhan721** [comment]
use backticks ( `` ) 
`<h4>${item.title}</h4>`

**Comment by MANSHU03** [comment]
use backticks `` instead of ""
